---
- name: Mount NFS Media folder
  hosts: plex-servers,docker-hosts
  become_user: root
  become: yes
  tasks:
    - name: Create folder for media
      file:
        path: /mnt/media
        state: directory
        mode: 0777
        owner: root
        group: root
    - name: Mount media folder
      mount:
        path: /mnt/media
        src: 172.16.1.6:/volume1/Media
        state: present
        fstype: nfs