---
- name: Create reverse proxy for services
  hosts: reverseproxy-servers
  become_user: root
  become: yes
  vars:
    nginx_server_list:
    - name: "sonarr.home.cardboardbox.be"
      delete: False
      listen: 
        - ["80"]
      access_log: "/var/log/nginx/sonarr_access.log"
      location_list:
        - name: "/"
          proxy_pass: "http://srv-docker-01:8989"
          proxy_set_header X-Real-IP: "$remote_addr"
          proxy_set_header Host: "$host"
          proxy_set_header X-Forwarded-For: "$proxy_add_x_forwarded_for"
          proxy_set_header X-Forwarded-Proto: "$scheme"
          proxy_redirect: "off"
    - name: "radarr.home.cardboardbox.be"
      delete: False
      listen: 
        - ["80"]
      access_log: "/var/log/nginx/radarr_access.log"
      location_list:
        - name: "/"
          proxy_pass: "http://srv-docker-01:7878"
          proxy_set_header X-Real-IP: "$remote_addr"
          proxy_set_header Host: "$host"
          proxy_set_header X-Forwarded-For: "$proxy_add_x_forwarded_for"
          proxy_set_header X-Forwarded-Proto: "$scheme"
          proxy_redirect: "off"
    - name: "deluge.home.cardboardbox.be"
      delete: False
      listen: 
        - ["80"]
      access_log: "/var/log/nginx/deluge_access.log"
      location_list:
        - name: "/"
          proxy_pass: "http://srv-docker-01:8112"
          proxy_set_header X-Real-IP: "$remote_addr"
          proxy_set_header Host: "$host"
          proxy_set_header X-Forwarded-For: "$proxy_add_x_forwarded_for"
          proxy_set_header X-Forwarded-Proto: "$scheme"
          proxy_redirect: "off"
  roles:
  - jriguera.nginx
  tasks:
  - name: Open firewall
    firewalld:
      service: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    with_items:
    - http
    - https
