---
- name: Install Plex
  hosts: plex-servers
  become_user: root
  become: yes
  tasks:
  - name: Install
    yum:
      name: https://downloads.plex.tv/plex-media-server/1.3.3.3148-b38628e/plexmediaserver-1.3.3.3148-b38628e.x86_64.rpm
      state: present
  - name: Configure firewalld
    firewalld:
      port: 32400/tcp
      permanent: true
      state: enabled
  - name: Enable and start service
    systemd:
      name: plexmediaserver
      state: started
      enabled: true