---
- hosts: all
  remote_user: wolfgang
  tasks:
  - name: get dotfiles
    shell: git clone https://github.com/woll0r/dotfiles.git ~/dotfiles
    args:
      creates: ~/dotfiles/
  - name: get oh-my-zsh
    shell: git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
    args:
      creates: ~/.oh-my-zsh
  - name: get .zshrc state
    stat:
      path: ~/.zshrc
    register: zshrc
  - name: delete the old .zshrc
    file:
      path: ~/.zshrc
      state: absent
    unless: zshrc.stat.islnk is defined and zshrc.stat.islnk
  - name: create .ssh directory
    file:
      path: ~/.ssh
      state: directory
  - name: stow the config files
    shell: stow screen zsh git ssh
    args:
      chdir: ~/dotfiles/
